import Login from "../../../books/login";

import Head from "next/head";

const Settings = () => {
    
    return (
        <>
            <Head>
                <title>Chillhub - Settings</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/chillhub.png" />
            </Head>
            <main>
                <Login />
            </main>
        </>
    )
}

export default Settings