import Head from "next/head";

import LoginPage from "../components/login/login";

const Login = () => {
  return (
    <>
      <Head>
        <title>Valentino Andric</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/pfp.jpg" />
      </Head>
      
      <main>
        <LoginPage />
      </main>
    </>
  );
};

export default Login;