import { type NextPage } from "next";
import Head from "next/head"; 

import Navbar from "../../components/components/navbar-daisy/navbar";
import Uv from "../../components/components/under-navbar/uv";

import About from "../../components/components/about/about";
import Projecten from "../../components/components/projecten/projecten";
import { ScrollToTop } from "../../components/components/scrolltotop/ScrollToTop";
import Form from "../../components/components/form/From";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Valentino Andric</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/pfp.jpg" />
      </Head>
      
      <main>
        <ScrollToTop />
        <Navbar />
        <Uv />
        <About />
        <Projecten />
        <Form />
      </main>
    </>
  );
};

export default Home;