import { type NextPage } from "next";
import Head from "next/head"; 

import Navbar from "../../components/navbar-daisy/navbar";
import Uv from "../../components/under-navbar/uv";

import Line from "../../components/line/line";
import About from "../../components/about/about";
import Talen from "../../components/talen/talen";
import Form from "../../components/form/form";
import { ScrollToTop } from "../../components/scrolltotop/ScrollToTop";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Valentino Andric</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/pfp.jpg" />
      </Head>
      
      <main>
        <ScrollToTop />
        <Navbar />
        <Uv />
        <About />
        <Talen />
        <Form />
      </main>
    </>
  );
};

export default Home;
