import Head from "next/head";

import { useSession } from "next-auth/react";

import Admin from "../../../components/admin";


const Books = () => {
    const { data: session, status } = useSession();

    if (status == "authenticated") {
        return (
            <>
            <Head>
                <title>Valentino Andric</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/pfp.jpg" />
            </Head>
            <main>
                <Admin />
            </main>
            </>
        )
    }

    return (
        <>
            <Head>
                <title>Valentino Andric</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/pfp.jpg" />
            </Head>
        </>
    )
}

export default Books;